package tr.edu.hacettepe.tokenize;

import java.util.HashSet;
import java.util.Hashtable;
import java.util.Set;


@SuppressWarnings("WeakerAccess")
public class EnglishStopwordList {

    /**
     * The hashtable containing the list of stopwords
     */
    private static Hashtable<String, Double> mapStopwords = null;

    static {

        if (mapStopwords == null) {
            mapStopwords = new Hashtable<>();
            Double dummy = 0d;

            mapStopwords.put("a", dummy);
            mapStopwords.put("after", dummy);
            mapStopwords.put("aint", dummy);
            mapStopwords.put("albeit", dummy);
            mapStopwords.put("all", dummy);
            mapStopwords.put("almost", dummy);
            mapStopwords.put("also", dummy);
            mapStopwords.put("although", dummy);
            mapStopwords.put("am", dummy);
            mapStopwords.put("among", dummy);
            mapStopwords.put("an", dummy);
            mapStopwords.put("and", dummy);
            mapStopwords.put("another", dummy);
            mapStopwords.put("any", dummy);
            mapStopwords.put("anybody", dummy);
            mapStopwords.put("anyone", dummy);
            mapStopwords.put("anything", dummy);
            mapStopwords.put("are", dummy);
            mapStopwords.put("aren't", dummy);
            mapStopwords.put("as", dummy);
            mapStopwords.put("at", dummy);
            mapStopwords.put("away", dummy);
            mapStopwords.put("b", dummy);
            mapStopwords.put("be", dummy);
            mapStopwords.put("because", dummy);
            mapStopwords.put("been", dummy);
            mapStopwords.put("before", dummy);
            mapStopwords.put("being", dummy);
            mapStopwords.put("between", dummy);
            mapStopwords.put("both", dummy);
            mapStopwords.put("but", dummy);
            mapStopwords.put("by", dummy);
            mapStopwords.put("c", dummy);
            mapStopwords.put("can", dummy);
            mapStopwords.put("cannot", dummy);
            mapStopwords.put("can't", dummy);
            mapStopwords.put("certain", dummy);
            mapStopwords.put("could", dummy);
            mapStopwords.put("couldn't", dummy);
            mapStopwords.put("couldst", dummy);
            mapStopwords.put("d", dummy);
            mapStopwords.put("despite", dummy);
            mapStopwords.put("did", dummy);
            mapStopwords.put("didn't", dummy);
            mapStopwords.put("do", dummy);
            mapStopwords.put("does", dummy);
            mapStopwords.put("doesn't", dummy);
            mapStopwords.put("doing", dummy);
            mapStopwords.put("done", dummy);
            mapStopwords.put("don't", dummy);
            mapStopwords.put("dost", dummy);
            mapStopwords.put("doth", dummy);
            mapStopwords.put("durst", dummy);
            mapStopwords.put("e", dummy);
            mapStopwords.put("each", dummy);
            mapStopwords.put("either", dummy);
            mapStopwords.put("em", dummy);
            mapStopwords.put("ere", dummy);
            mapStopwords.put("even", dummy);
            mapStopwords.put("ever", dummy);
            mapStopwords.put("every", dummy);
            mapStopwords.put("everybody", dummy);
            mapStopwords.put("everyone", dummy);
            mapStopwords.put("everything", dummy);
            mapStopwords.put("few", dummy);
            mapStopwords.put("for", dummy);
            mapStopwords.put("from", dummy);
            mapStopwords.put("g", dummy);
            mapStopwords.put("gonna", dummy);
            mapStopwords.put("gotta", dummy);
            mapStopwords.put("h", dummy);
            mapStopwords.put("had", dummy);
            mapStopwords.put("hadn't", dummy);
            mapStopwords.put("hard", dummy);
            mapStopwords.put("has", dummy);
            mapStopwords.put("hasn't", dummy);
            mapStopwords.put("hast", dummy);
            mapStopwords.put("hath", dummy);
            mapStopwords.put("have", dummy);
            mapStopwords.put("haven't", dummy);
            mapStopwords.put("having", dummy);
            mapStopwords.put("he", dummy);
            mapStopwords.put("he'd", dummy);
            mapStopwords.put("he'll", dummy);
            mapStopwords.put("her", dummy);
            mapStopwords.put("here", dummy);
            mapStopwords.put("here's", dummy);
            mapStopwords.put("hers", dummy);
            mapStopwords.put("herself", dummy);
            mapStopwords.put("he's", dummy);
            mapStopwords.put("him", dummy);
            mapStopwords.put("himself", dummy);
            mapStopwords.put("his", dummy);
            mapStopwords.put("how", dummy);
            mapStopwords.put("however", dummy);
            mapStopwords.put("how's", dummy);
            mapStopwords.put("i", dummy);
            mapStopwords.put("id", dummy);
            mapStopwords.put("if", dummy);
            mapStopwords.put("i'm", dummy);
            mapStopwords.put("in", dummy);
            mapStopwords.put("is", dummy);
            mapStopwords.put("isn't", dummy);
            mapStopwords.put("it", dummy);
            mapStopwords.put("it'll", dummy);
            mapStopwords.put("it's", dummy);
            mapStopwords.put("its", dummy);
            mapStopwords.put("itself", dummy);
            mapStopwords.put("i've", dummy);
            mapStopwords.put("j", dummy);
            mapStopwords.put("k", dummy);
            mapStopwords.put("l", dummy);
            mapStopwords.put("later", dummy);
            mapStopwords.put("let's", dummy);
            mapStopwords.put("like", dummy);
            mapStopwords.put("likewise", dummy);
            mapStopwords.put("m", dummy);
            mapStopwords.put("many", dummy);
            mapStopwords.put("may", dummy);
            mapStopwords.put("mayn't", dummy);
            mapStopwords.put("me", dummy);
            mapStopwords.put("might", dummy);
            mapStopwords.put("mightn't", dummy);
            mapStopwords.put("mine", dummy);
            mapStopwords.put("more", dummy);
            mapStopwords.put("most", dummy);
            mapStopwords.put("much", dummy);
            mapStopwords.put("must", dummy);
            mapStopwords.put("mustn't", dummy);
            mapStopwords.put("my", dummy);
            mapStopwords.put("myself", dummy);
            mapStopwords.put("n", dummy);
            mapStopwords.put("needn't", dummy);
            mapStopwords.put("neither", dummy);
            mapStopwords.put("nevertheless", dummy);
            mapStopwords.put("nisi", dummy);
            mapStopwords.put("no", dummy);
            mapStopwords.put("nobody", dummy);
            mapStopwords.put("none", dummy);
            mapStopwords.put("nor", dummy);
            mapStopwords.put("not", dummy);
            mapStopwords.put("nothing", dummy);
            mapStopwords.put("now", dummy);
            mapStopwords.put("o", dummy);
            mapStopwords.put("o'er", dummy);
            mapStopwords.put("of", dummy);
            mapStopwords.put("often", dummy);
            mapStopwords.put("on", dummy);
            mapStopwords.put("only", dummy);
            mapStopwords.put("or", dummy);
            mapStopwords.put("other", dummy);
            mapStopwords.put("ought", dummy);
            mapStopwords.put("oughtn't", dummy);
            mapStopwords.put("our", dummy);
            mapStopwords.put("ours", dummy);
            mapStopwords.put("ourselves", dummy);
            mapStopwords.put("p", dummy);
            mapStopwords.put("possible", dummy);
            mapStopwords.put("q", dummy);
            mapStopwords.put("r", dummy);
            mapStopwords.put("rather", dummy);
            mapStopwords.put("re", dummy);
            mapStopwords.put("s", dummy);
            mapStopwords.put("shall", dummy);
            mapStopwords.put("shalt", dummy);
            mapStopwords.put("shan't", dummy);
            mapStopwords.put("she", dummy);
            mapStopwords.put("shell", dummy);
            mapStopwords.put("she's", dummy);
            mapStopwords.put("should", dummy);
            mapStopwords.put("shouldn't", dummy);
            mapStopwords.put("so", dummy);
            mapStopwords.put("some", dummy);
            mapStopwords.put("somebody", dummy);
            mapStopwords.put("someone", dummy);
            mapStopwords.put("something", dummy);
            mapStopwords.put("sometimes", dummy);
            mapStopwords.put("soon", dummy);
            mapStopwords.put("still", dummy);
            mapStopwords.put("such", dummy);
            mapStopwords.put("t", dummy);
            mapStopwords.put("than", dummy);
            mapStopwords.put("that", dummy);
            mapStopwords.put("that'd", dummy);
            mapStopwords.put("that'll", dummy);
            mapStopwords.put("that's", dummy);
            mapStopwords.put("the", dummy);
            mapStopwords.put("thee", dummy);
            mapStopwords.put("their", dummy);
            mapStopwords.put("theirs", dummy);
            mapStopwords.put("their's", dummy);
            mapStopwords.put("them", dummy);
            mapStopwords.put("themselves", dummy);
            mapStopwords.put("then", dummy);
            mapStopwords.put("there", dummy);
            mapStopwords.put("there's", dummy);
            mapStopwords.put("these", dummy);
            mapStopwords.put("they", dummy);
            mapStopwords.put("they'd", dummy);
            mapStopwords.put("they'll", dummy);
            mapStopwords.put("they're", dummy);
            mapStopwords.put("they've", dummy);
            mapStopwords.put("this", dummy);
            mapStopwords.put("tho", dummy);
            mapStopwords.put("those", dummy);
            mapStopwords.put("thou", dummy);
            mapStopwords.put("though", dummy);
            mapStopwords.put("through", dummy);
            mapStopwords.put("throughout", dummy);
            mapStopwords.put("thyself", dummy);
            mapStopwords.put("till", dummy);
            mapStopwords.put("to", dummy);
            mapStopwords.put("too", dummy);
            mapStopwords.put("toward", dummy);
            mapStopwords.put("towards", dummy);
            mapStopwords.put("u", dummy);
            mapStopwords.put("unless", dummy);
            mapStopwords.put("until", dummy);
            mapStopwords.put("us", dummy);
            mapStopwords.put("usually", dummy);
            mapStopwords.put("v", dummy);
            mapStopwords.put("via", dummy);
            mapStopwords.put("vis-a-vis", dummy);
            mapStopwords.put("w", dummy);
            mapStopwords.put("wanna", dummy);
            mapStopwords.put("was", dummy);
            mapStopwords.put("wasn't", dummy);
            mapStopwords.put("way", dummy);
            mapStopwords.put("we", dummy);
            mapStopwords.put("we'd", dummy);
            mapStopwords.put("well", dummy);
            mapStopwords.put("were", dummy);
            mapStopwords.put("weren't", dummy);
            mapStopwords.put("wert", dummy);
            mapStopwords.put("we've", dummy);
            mapStopwords.put("what", dummy);
            mapStopwords.put("whatever", dummy);
            mapStopwords.put("what'll", dummy);
            mapStopwords.put("what's", dummy);
            mapStopwords.put("when", dummy);
            mapStopwords.put("whenever", dummy);
            mapStopwords.put("when's", dummy);
            mapStopwords.put("whereas", dummy);
            mapStopwords.put("where's", dummy);
            mapStopwords.put("whether", dummy);
            mapStopwords.put("which", dummy);
            mapStopwords.put("whichever", dummy);
            mapStopwords.put("whichsoever", dummy);
            mapStopwords.put("while", dummy);
            mapStopwords.put("whilst", dummy);
            mapStopwords.put("who", dummy);
            mapStopwords.put("who'd", dummy);
            mapStopwords.put("whoever", dummy);
            mapStopwords.put("whole", dummy);
            mapStopwords.put("who'll", dummy);
            mapStopwords.put("whom", dummy);
            mapStopwords.put("whore", dummy);
            mapStopwords.put("who's", dummy);
            mapStopwords.put("whose", dummy);
            mapStopwords.put("whoso", dummy);
            mapStopwords.put("whosoever", dummy);
            mapStopwords.put("will", dummy);
            mapStopwords.put("with", dummy);
            mapStopwords.put("within", dummy);
            mapStopwords.put("without", dummy);
            mapStopwords.put("wont", dummy);
            mapStopwords.put("would", dummy);
            mapStopwords.put("wouldn't", dummy);
            mapStopwords.put("wouldst", dummy);
            mapStopwords.put("x", dummy);
            mapStopwords.put("y", dummy);
            mapStopwords.put("ye", dummy);
            mapStopwords.put("yet", dummy);
            mapStopwords.put("you", dummy);
            mapStopwords.put("you'd", dummy);
            mapStopwords.put("you'll", dummy);
            mapStopwords.put("your", dummy);
            mapStopwords.put("you're", dummy);
            mapStopwords.put("yours", dummy);
            mapStopwords.put("yourself", dummy);
            mapStopwords.put("yourselves", dummy);
            mapStopwords.put("you've", dummy);
            mapStopwords.put("z", dummy);
            mapStopwords.put("ref", dummy);

            Set<String> set = new HashSet<>(mapStopwords.keySet());
            for (String string : set) {
                mapStopwords.put(string, dummy);
            }
        }
    }

    /**
     * Returns true if the given string is a stop word.
     */
    public boolean isStopword(String str) {
        return str.length() == 1 || mapStopwords.containsKey(str.toLowerCase());

    }

}
